/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyResult service. Represents a row in the &quot;lc_SurveyResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyResultImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyResult
 * @see com.lc.survey.model.impl.SurveyResultImpl
 * @see com.lc.survey.model.impl.SurveyResultModelImpl
 * @generated
 */
public interface SurveyResultModel extends BaseModel<SurveyResult> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey result model instance should use the {@link SurveyResult} interface instead.
	 */

	/**
	 * Returns the primary key of this survey result.
	 *
	 * @return the primary key of this survey result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey result.
	 *
	 * @param primaryKey the primary key of this survey result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey result ID of this survey result.
	 *
	 * @return the survey result ID of this survey result
	 */
	public long getSurveyResultId();

	/**
	 * Sets the survey result ID of this survey result.
	 *
	 * @param surveyResultId the survey result ID of this survey result
	 */
	public void setSurveyResultId(long surveyResultId);

	/**
	 * Returns the survey main ID of this survey result.
	 *
	 * @return the survey main ID of this survey result
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey result.
	 *
	 * @param surveyMainId the survey main ID of this survey result
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the survey page ID of this survey result.
	 *
	 * @return the survey page ID of this survey result
	 */
	public long getSurveyPageId();

	/**
	 * Sets the survey page ID of this survey result.
	 *
	 * @param surveyPageId the survey page ID of this survey result
	 */
	public void setSurveyPageId(long surveyPageId);

	/**
	 * Returns the survey question ID of this survey result.
	 *
	 * @return the survey question ID of this survey result
	 */
	public long getSurveyQuestionId();

	/**
	 * Sets the survey question ID of this survey result.
	 *
	 * @param surveyQuestionId the survey question ID of this survey result
	 */
	public void setSurveyQuestionId(long surveyQuestionId);

	/**
	 * Returns the survey option ID of this survey result.
	 *
	 * @return the survey option ID of this survey result
	 */
	public long getSurveyOptionId();

	/**
	 * Sets the survey option ID of this survey result.
	 *
	 * @param surveyOptionId the survey option ID of this survey result
	 */
	public void setSurveyOptionId(long surveyOptionId);

	/**
	 * Returns the survey writer ID of this survey result.
	 *
	 * @return the survey writer ID of this survey result
	 */
	public long getSurveyWriterId();

	/**
	 * Sets the survey writer ID of this survey result.
	 *
	 * @param surveyWriterId the survey writer ID of this survey result
	 */
	public void setSurveyWriterId(long surveyWriterId);

	/**
	 * Returns the ans of this survey result.
	 *
	 * @return the ans of this survey result
	 */
	@AutoEscape
	public String getAns();

	/**
	 * Sets the ans of this survey result.
	 *
	 * @param ans the ans of this survey result
	 */
	public void setAns(String ans);

	/**
	 * Returns the creator ID of this survey result.
	 *
	 * @return the creator ID of this survey result
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey result.
	 *
	 * @param creatorId the creator ID of this survey result
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this survey result.
	 *
	 * @return the create date of this survey result
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey result.
	 *
	 * @param createDate the create date of this survey result
	 */
	public void setCreateDate(long createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyResult surveyResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyResult> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyResult toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}