/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyPage service. Represents a row in the &quot;lc_SurveyPage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyPageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyPageImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyPage
 * @see com.lc.survey.model.impl.SurveyPageImpl
 * @see com.lc.survey.model.impl.SurveyPageModelImpl
 * @generated
 */
public interface SurveyPageModel extends BaseModel<SurveyPage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey page model instance should use the {@link SurveyPage} interface instead.
	 */

	/**
	 * Returns the primary key of this survey page.
	 *
	 * @return the primary key of this survey page
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey page.
	 *
	 * @param primaryKey the primary key of this survey page
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey page ID of this survey page.
	 *
	 * @return the survey page ID of this survey page
	 */
	public long getSurveyPageId();

	/**
	 * Sets the survey page ID of this survey page.
	 *
	 * @param surveyPageId the survey page ID of this survey page
	 */
	public void setSurveyPageId(long surveyPageId);

	/**
	 * Returns the survey main ID of this survey page.
	 *
	 * @return the survey main ID of this survey page
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey page.
	 *
	 * @param surveyMainId the survey main ID of this survey page
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the no of this survey page.
	 *
	 * @return the no of this survey page
	 */
	public int getNo();

	/**
	 * Sets the no of this survey page.
	 *
	 * @param no the no of this survey page
	 */
	public void setNo(int no);

	/**
	 * Returns the title of this survey page.
	 *
	 * @return the title of this survey page
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this survey page.
	 *
	 * @param title the title of this survey page
	 */
	public void setTitle(String title);

	/**
	 * Returns the page direct ID of this survey page.
	 *
	 * @return the page direct ID of this survey page
	 */
	public long getPageDirectId();

	/**
	 * Sets the page direct ID of this survey page.
	 *
	 * @param pageDirectId the page direct ID of this survey page
	 */
	public void setPageDirectId(long pageDirectId);

	/**
	 * Returns the creator ID of this survey page.
	 *
	 * @return the creator ID of this survey page
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey page.
	 *
	 * @param creatorId the creator ID of this survey page
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the modifier ID of this survey page.
	 *
	 * @return the modifier ID of this survey page
	 */
	public long getModifierId();

	/**
	 * Sets the modifier ID of this survey page.
	 *
	 * @param modifierId the modifier ID of this survey page
	 */
	public void setModifierId(long modifierId);

	/**
	 * Returns the create date of this survey page.
	 *
	 * @return the create date of this survey page
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey page.
	 *
	 * @param createDate the create date of this survey page
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the modified date of this survey page.
	 *
	 * @return the modified date of this survey page
	 */
	public long getModifiedDate();

	/**
	 * Sets the modified date of this survey page.
	 *
	 * @param modifiedDate the modified date of this survey page
	 */
	public void setModifiedDate(long modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyPage surveyPage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyPage> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyPage toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyPage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}