/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyFile service. Represents a row in the &quot;lc_SurveyFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyFileImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyFile
 * @see com.lc.survey.model.impl.SurveyFileImpl
 * @see com.lc.survey.model.impl.SurveyFileModelImpl
 * @generated
 */
public interface SurveyFileModel extends BaseModel<SurveyFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey file model instance should use the {@link SurveyFile} interface instead.
	 */

	/**
	 * Returns the primary key of this survey file.
	 *
	 * @return the primary key of this survey file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey file.
	 *
	 * @param primaryKey the primary key of this survey file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey file ID of this survey file.
	 *
	 * @return the survey file ID of this survey file
	 */
	public long getSurveyFileId();

	/**
	 * Sets the survey file ID of this survey file.
	 *
	 * @param surveyFileId the survey file ID of this survey file
	 */
	public void setSurveyFileId(long surveyFileId);

	/**
	 * Returns the survey main ID of this survey file.
	 *
	 * @return the survey main ID of this survey file
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey file.
	 *
	 * @param surveyMainId the survey main ID of this survey file
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the file name of this survey file.
	 *
	 * @return the file name of this survey file
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this survey file.
	 *
	 * @param fileName the file name of this survey file
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the creator ID of this survey file.
	 *
	 * @return the creator ID of this survey file
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey file.
	 *
	 * @param creatorId the creator ID of this survey file
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this survey file.
	 *
	 * @return the create date of this survey file
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey file.
	 *
	 * @param createDate the create date of this survey file
	 */
	public void setCreateDate(long createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyFile surveyFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyFile> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyFile toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}