/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyWriter service. Represents a row in the &quot;lc_SurveyWriter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyWriterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyWriterImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyWriter
 * @see com.lc.survey.model.impl.SurveyWriterImpl
 * @see com.lc.survey.model.impl.SurveyWriterModelImpl
 * @generated
 */
public interface SurveyWriterModel extends BaseModel<SurveyWriter> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey writer model instance should use the {@link SurveyWriter} interface instead.
	 */

	/**
	 * Returns the primary key of this survey writer.
	 *
	 * @return the primary key of this survey writer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey writer.
	 *
	 * @param primaryKey the primary key of this survey writer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey writer ID of this survey writer.
	 *
	 * @return the survey writer ID of this survey writer
	 */
	public long getSurveyWriterId();

	/**
	 * Sets the survey writer ID of this survey writer.
	 *
	 * @param surveyWriterId the survey writer ID of this survey writer
	 */
	public void setSurveyWriterId(long surveyWriterId);

	/**
	 * Returns the survey main ID of this survey writer.
	 *
	 * @return the survey main ID of this survey writer
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey writer.
	 *
	 * @param surveyMainId the survey main ID of this survey writer
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the is preview of this survey writer.
	 *
	 * @return the is preview of this survey writer
	 */
	public Boolean getIsPreview();

	/**
	 * Sets the is preview of this survey writer.
	 *
	 * @param isPreview the is preview of this survey writer
	 */
	public void setIsPreview(Boolean isPreview);

	/**
	 * Returns the is complete of this survey writer.
	 *
	 * @return the is complete of this survey writer
	 */
	public Boolean getIsComplete();

	/**
	 * Sets the is complete of this survey writer.
	 *
	 * @param isComplete the is complete of this survey writer
	 */
	public void setIsComplete(Boolean isComplete);

	/**
	 * Returns the completion time of this survey writer.
	 *
	 * @return the completion time of this survey writer
	 */
	public long getCompletionTime();

	/**
	 * Sets the completion time of this survey writer.
	 *
	 * @param completionTime the completion time of this survey writer
	 */
	public void setCompletionTime(long completionTime);

	/**
	 * Returns the creator ID of this survey writer.
	 *
	 * @return the creator ID of this survey writer
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey writer.
	 *
	 * @param creatorId the creator ID of this survey writer
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this survey writer.
	 *
	 * @return the create date of this survey writer
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey writer.
	 *
	 * @param createDate the create date of this survey writer
	 */
	public void setCreateDate(long createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyWriter surveyWriter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyWriter> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyWriter toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyWriter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}