/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyQuestion service. Represents a row in the &quot;lc_SurveyQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyQuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyQuestionImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyQuestion
 * @see com.lc.survey.model.impl.SurveyQuestionImpl
 * @see com.lc.survey.model.impl.SurveyQuestionModelImpl
 * @generated
 */
public interface SurveyQuestionModel extends BaseModel<SurveyQuestion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey question model instance should use the {@link SurveyQuestion} interface instead.
	 */

	/**
	 * Returns the primary key of this survey question.
	 *
	 * @return the primary key of this survey question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey question.
	 *
	 * @param primaryKey the primary key of this survey question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey question ID of this survey question.
	 *
	 * @return the survey question ID of this survey question
	 */
	public long getSurveyQuestionId();

	/**
	 * Sets the survey question ID of this survey question.
	 *
	 * @param surveyQuestionId the survey question ID of this survey question
	 */
	public void setSurveyQuestionId(long surveyQuestionId);

	/**
	 * Returns the survey main ID of this survey question.
	 *
	 * @return the survey main ID of this survey question
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey question.
	 *
	 * @param surveyMainId the survey main ID of this survey question
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the survey page ID of this survey question.
	 *
	 * @return the survey page ID of this survey question
	 */
	public long getSurveyPageId();

	/**
	 * Sets the survey page ID of this survey question.
	 *
	 * @param surveyPageId the survey page ID of this survey question
	 */
	public void setSurveyPageId(long surveyPageId);

	/**
	 * Returns the parent ID of this survey question.
	 *
	 * @return the parent ID of this survey question
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this survey question.
	 *
	 * @param parentId the parent ID of this survey question
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the no of this survey question.
	 *
	 * @return the no of this survey question
	 */
	public int getNo();

	/**
	 * Sets the no of this survey question.
	 *
	 * @param no the no of this survey question
	 */
	public void setNo(int no);

	/**
	 * Returns the question of this survey question.
	 *
	 * @return the question of this survey question
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this survey question.
	 *
	 * @param question the question of this survey question
	 */
	public void setQuestion(String question);

	/**
	 * Returns the type of this survey question.
	 *
	 * @return the type of this survey question
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this survey question.
	 *
	 * @param type the type of this survey question
	 */
	public void setType(String type);

	/**
	 * Returns the is required of this survey question.
	 *
	 * @return the is required of this survey question
	 */
	public Boolean getIsRequired();

	/**
	 * Sets the is required of this survey question.
	 *
	 * @param isRequired the is required of this survey question
	 */
	public void setIsRequired(Boolean isRequired);

	/**
	 * Returns the has other of this survey question.
	 *
	 * @return the has other of this survey question
	 */
	public Boolean getHasOther();

	/**
	 * Sets the has other of this survey question.
	 *
	 * @param hasOther the has other of this survey question
	 */
	public void setHasOther(Boolean hasOther);

	/**
	 * Returns the option direct of this survey question.
	 *
	 * @return the option direct of this survey question
	 */
	public Boolean getOptionDirect();

	/**
	 * Sets the option direct of this survey question.
	 *
	 * @param optionDirect the option direct of this survey question
	 */
	public void setOptionDirect(Boolean optionDirect);

	/**
	 * Returns the points of this survey question.
	 *
	 * @return the points of this survey question
	 */
	@AutoEscape
	public String getPoints();

	/**
	 * Sets the points of this survey question.
	 *
	 * @param points the points of this survey question
	 */
	public void setPoints(String points);

	/**
	 * Returns the stars count of this survey question.
	 *
	 * @return the stars count of this survey question
	 */
	public int getStarsCount();

	/**
	 * Sets the stars count of this survey question.
	 *
	 * @param starsCount the stars count of this survey question
	 */
	public void setStarsCount(int starsCount);

	/**
	 * Returns the upload file ID of this survey question.
	 *
	 * @return the upload file ID of this survey question
	 */
	public long getUploadFileId();

	/**
	 * Sets the upload file ID of this survey question.
	 *
	 * @param uploadFileId the upload file ID of this survey question
	 */
	public void setUploadFileId(long uploadFileId);

	/**
	 * Returns the creator ID of this survey question.
	 *
	 * @return the creator ID of this survey question
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey question.
	 *
	 * @param creatorId the creator ID of this survey question
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the modifier ID of this survey question.
	 *
	 * @return the modifier ID of this survey question
	 */
	public long getModifierId();

	/**
	 * Sets the modifier ID of this survey question.
	 *
	 * @param modifierId the modifier ID of this survey question
	 */
	public void setModifierId(long modifierId);

	/**
	 * Returns the create date of this survey question.
	 *
	 * @return the create date of this survey question
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey question.
	 *
	 * @param createDate the create date of this survey question
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the modified date of this survey question.
	 *
	 * @return the modified date of this survey question
	 */
	public long getModifiedDate();

	/**
	 * Sets the modified date of this survey question.
	 *
	 * @param modifiedDate the modified date of this survey question
	 */
	public void setModifiedDate(long modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyQuestion surveyQuestion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyQuestion> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyQuestion toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyQuestion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}