/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyWriteSequence service. Represents a row in the &quot;lc_SurveyWriteSequence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyWriteSequenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyWriteSequenceImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyWriteSequence
 * @see com.lc.survey.model.impl.SurveyWriteSequenceImpl
 * @see com.lc.survey.model.impl.SurveyWriteSequenceModelImpl
 * @generated
 */
public interface SurveyWriteSequenceModel extends BaseModel<SurveyWriteSequence> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey write sequence model instance should use the {@link SurveyWriteSequence} interface instead.
	 */

	/**
	 * Returns the primary key of this survey write sequence.
	 *
	 * @return the primary key of this survey write sequence
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey write sequence.
	 *
	 * @param primaryKey the primary key of this survey write sequence
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey write sequence ID of this survey write sequence.
	 *
	 * @return the survey write sequence ID of this survey write sequence
	 */
	public long getSurveyWriteSequenceId();

	/**
	 * Sets the survey write sequence ID of this survey write sequence.
	 *
	 * @param surveyWriteSequenceId the survey write sequence ID of this survey write sequence
	 */
	public void setSurveyWriteSequenceId(long surveyWriteSequenceId);

	/**
	 * Returns the survey writer ID of this survey write sequence.
	 *
	 * @return the survey writer ID of this survey write sequence
	 */
	public long getSurveyWriterId();

	/**
	 * Sets the survey writer ID of this survey write sequence.
	 *
	 * @param surveyWriterId the survey writer ID of this survey write sequence
	 */
	public void setSurveyWriterId(long surveyWriterId);

	/**
	 * Returns the page ID of this survey write sequence.
	 *
	 * @return the page ID of this survey write sequence
	 */
	public long getPageId();

	/**
	 * Sets the page ID of this survey write sequence.
	 *
	 * @param pageId the page ID of this survey write sequence
	 */
	public void setPageId(long pageId);

	/**
	 * Returns the pre page ID of this survey write sequence.
	 *
	 * @return the pre page ID of this survey write sequence
	 */
	public long getPrePageId();

	/**
	 * Sets the pre page ID of this survey write sequence.
	 *
	 * @param prePageId the pre page ID of this survey write sequence
	 */
	public void setPrePageId(long prePageId);

	/**
	 * Returns the is direct of this survey write sequence.
	 *
	 * @return the is direct of this survey write sequence
	 */
	public Boolean getIsDirect();

	/**
	 * Sets the is direct of this survey write sequence.
	 *
	 * @param isDirect the is direct of this survey write sequence
	 */
	public void setIsDirect(Boolean isDirect);

	/**
	 * Returns the creator ID of this survey write sequence.
	 *
	 * @return the creator ID of this survey write sequence
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey write sequence.
	 *
	 * @param creatorId the creator ID of this survey write sequence
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this survey write sequence.
	 *
	 * @return the create date of this survey write sequence
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey write sequence.
	 *
	 * @param createDate the create date of this survey write sequence
	 */
	public void setCreateDate(long createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.lc.survey.model.SurveyWriteSequence surveyWriteSequence);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyWriteSequence> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyWriteSequence toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyWriteSequence toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}