/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SurveyMain service. Represents a row in the &quot;lc_SurveyMain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyMainModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyMainImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyMain
 * @see com.lc.survey.model.impl.SurveyMainImpl
 * @see com.lc.survey.model.impl.SurveyMainModelImpl
 * @generated
 */
public interface SurveyMainModel extends BaseModel<SurveyMain> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey main model instance should use the {@link SurveyMain} interface instead.
	 */

	/**
	 * Returns the primary key of this survey main.
	 *
	 * @return the primary key of this survey main
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey main.
	 *
	 * @param primaryKey the primary key of this survey main
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey main ID of this survey main.
	 *
	 * @return the survey main ID of this survey main
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey main.
	 *
	 * @param surveyMainId the survey main ID of this survey main
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the title of this survey main.
	 *
	 * @return the title of this survey main
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this survey main.
	 *
	 * @param title the title of this survey main
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this survey main.
	 *
	 * @return the description of this survey main
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this survey main.
	 *
	 * @param description the description of this survey main
	 */
	public void setDescription(String description);

	/**
	 * Returns the epilog of this survey main.
	 *
	 * @return the epilog of this survey main
	 */
	@AutoEscape
	public String getEpilog();

	/**
	 * Sets the epilog of this survey main.
	 *
	 * @param epilog the epilog of this survey main
	 */
	public void setEpilog(String epilog);

	/**
	 * Returns the start date of this survey main.
	 *
	 * @return the start date of this survey main
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this survey main.
	 *
	 * @param startDate the start date of this survey main
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this survey main.
	 *
	 * @return the end date of this survey main
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this survey main.
	 *
	 * @param endDate the end date of this survey main
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the need auth of this survey main.
	 *
	 * @return the need auth of this survey main
	 */
	public Boolean getNeedAuth();

	/**
	 * Sets the need auth of this survey main.
	 *
	 * @param needAuth the need auth of this survey main
	 */
	public void setNeedAuth(Boolean needAuth);

	/**
	 * Returns the calculate score of this survey main.
	 *
	 * @return the calculate score of this survey main
	 */
	public Boolean getCalculateScore();

	/**
	 * Sets the calculate score of this survey main.
	 *
	 * @param calculateScore the calculate score of this survey main
	 */
	public void setCalculateScore(Boolean calculateScore);

	/**
	 * Returns the view answer of this survey main.
	 *
	 * @return the view answer of this survey main
	 */
	public Boolean getViewAnswer();

	/**
	 * Sets the view answer of this survey main.
	 *
	 * @param viewAnswer the view answer of this survey main
	 */
	public void setViewAnswer(Boolean viewAnswer);

	/**
	 * Returns the color of this survey main.
	 *
	 * @return the color of this survey main
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this survey main.
	 *
	 * @param color the color of this survey main
	 */
	public void setColor(String color);

	/**
	 * Returns the creator ID of this survey main.
	 *
	 * @return the creator ID of this survey main
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey main.
	 *
	 * @param creatorId the creator ID of this survey main
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the modifier ID of this survey main.
	 *
	 * @return the modifier ID of this survey main
	 */
	public long getModifierId();

	/**
	 * Sets the modifier ID of this survey main.
	 *
	 * @param modifierId the modifier ID of this survey main
	 */
	public void setModifierId(long modifierId);

	/**
	 * Returns the create date of this survey main.
	 *
	 * @return the create date of this survey main
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey main.
	 *
	 * @param createDate the create date of this survey main
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the modified date of this survey main.
	 *
	 * @return the modified date of this survey main
	 */
	public long getModifiedDate();

	/**
	 * Sets the modified date of this survey main.
	 *
	 * @param modifiedDate the modified date of this survey main
	 */
	public void setModifiedDate(long modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyMain surveyMain);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyMain> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyMain toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyMain toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}