/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyOption service. Represents a row in the &quot;lc_SurveyOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lc.survey.model.impl.SurveyOptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lc.survey.model.impl.SurveyOptionImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyOption
 * @see com.lc.survey.model.impl.SurveyOptionImpl
 * @see com.lc.survey.model.impl.SurveyOptionModelImpl
 * @generated
 */
public interface SurveyOptionModel extends BaseModel<SurveyOption> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey option model instance should use the {@link SurveyOption} interface instead.
	 */

	/**
	 * Returns the primary key of this survey option.
	 *
	 * @return the primary key of this survey option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey option.
	 *
	 * @param primaryKey the primary key of this survey option
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the survey option ID of this survey option.
	 *
	 * @return the survey option ID of this survey option
	 */
	public long getSurveyOptionId();

	/**
	 * Sets the survey option ID of this survey option.
	 *
	 * @param surveyOptionId the survey option ID of this survey option
	 */
	public void setSurveyOptionId(long surveyOptionId);

	/**
	 * Returns the survey main ID of this survey option.
	 *
	 * @return the survey main ID of this survey option
	 */
	public long getSurveyMainId();

	/**
	 * Sets the survey main ID of this survey option.
	 *
	 * @param surveyMainId the survey main ID of this survey option
	 */
	public void setSurveyMainId(long surveyMainId);

	/**
	 * Returns the survey page ID of this survey option.
	 *
	 * @return the survey page ID of this survey option
	 */
	public long getSurveyPageId();

	/**
	 * Sets the survey page ID of this survey option.
	 *
	 * @param surveyPageId the survey page ID of this survey option
	 */
	public void setSurveyPageId(long surveyPageId);

	/**
	 * Returns the survey question ID of this survey option.
	 *
	 * @return the survey question ID of this survey option
	 */
	public long getSurveyQuestionId();

	/**
	 * Sets the survey question ID of this survey option.
	 *
	 * @param surveyQuestionId the survey question ID of this survey option
	 */
	public void setSurveyQuestionId(long surveyQuestionId);

	/**
	 * Returns the no of this survey option.
	 *
	 * @return the no of this survey option
	 */
	public int getNo();

	/**
	 * Sets the no of this survey option.
	 *
	 * @param no the no of this survey option
	 */
	public void setNo(int no);

	/**
	 * Returns the option of this survey option.
	 *
	 * @return the option of this survey option
	 */
	@AutoEscape
	public String getOption();

	/**
	 * Sets the option of this survey option.
	 *
	 * @param option the option of this survey option
	 */
	public void setOption(String option);

	/**
	 * Returns the is ans of this survey option.
	 *
	 * @return the is ans of this survey option
	 */
	public Boolean getIsAns();

	/**
	 * Sets the is ans of this survey option.
	 *
	 * @param isAns the is ans of this survey option
	 */
	public void setIsAns(Boolean isAns);

	/**
	 * Returns the page direct ID of this survey option.
	 *
	 * @return the page direct ID of this survey option
	 */
	public long getPageDirectId();

	/**
	 * Sets the page direct ID of this survey option.
	 *
	 * @param pageDirectId the page direct ID of this survey option
	 */
	public void setPageDirectId(long pageDirectId);

	/**
	 * Returns the upload file ID of this survey option.
	 *
	 * @return the upload file ID of this survey option
	 */
	public long getUploadFileId();

	/**
	 * Sets the upload file ID of this survey option.
	 *
	 * @param uploadFileId the upload file ID of this survey option
	 */
	public void setUploadFileId(long uploadFileId);

	/**
	 * Returns the creator ID of this survey option.
	 *
	 * @return the creator ID of this survey option
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this survey option.
	 *
	 * @param creatorId the creator ID of this survey option
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the modifier ID of this survey option.
	 *
	 * @return the modifier ID of this survey option
	 */
	public long getModifierId();

	/**
	 * Sets the modifier ID of this survey option.
	 *
	 * @param modifierId the modifier ID of this survey option
	 */
	public void setModifierId(long modifierId);

	/**
	 * Returns the create date of this survey option.
	 *
	 * @return the create date of this survey option
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this survey option.
	 *
	 * @param createDate the create date of this survey option
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the modified date of this survey option.
	 *
	 * @return the modified date of this survey option
	 */
	public long getModifiedDate();

	/**
	 * Sets the modified date of this survey option.
	 *
	 * @param modifiedDate the modified date of this survey option
	 */
	public void setModifiedDate(long modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.lc.survey.model.SurveyOption surveyOption);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.lc.survey.model.SurveyOption> toCacheModel();

	@Override
	public com.lc.survey.model.SurveyOption toEscapedModel();

	@Override
	public com.lc.survey.model.SurveyOption toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}