/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model.impl;

import com.lc.survey.model.SurveyWriter;
import com.lc.survey.model.SurveyWriterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SurveyWriter service. Represents a row in the &quot;lc_SurveyWriter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.lc.survey.model.SurveyWriterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveyWriterImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyWriterImpl
 * @see com.lc.survey.model.SurveyWriter
 * @see com.lc.survey.model.SurveyWriterModel
 * @generated
 */
public class SurveyWriterModelImpl extends BaseModelImpl<SurveyWriter>
	implements SurveyWriterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a survey writer model instance should use the {@link com.lc.survey.model.SurveyWriter} interface instead.
	 */
	public static final String TABLE_NAME = "lc_SurveyWriter";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surveyWriterId", Types.BIGINT },
			{ "surveyMainId", Types.BIGINT },
			{ "isPreview", Types.BOOLEAN },
			{ "isComplete", Types.BOOLEAN },
			{ "completionTime", Types.BIGINT },
			{ "creatorId", Types.BIGINT },
			{ "createDate", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table lc_SurveyWriter (surveyWriterId LONG not null primary key,surveyMainId LONG,isPreview BOOLEAN,isComplete BOOLEAN,completionTime LONG,creatorId LONG,createDate LONG)";
	public static final String TABLE_SQL_DROP = "drop table lc_SurveyWriter";
	public static final String ORDER_BY_JPQL = " ORDER BY surveyWriter.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY lc_SurveyWriter.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.lc.survey.model.SurveyWriter"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.lc.survey.model.SurveyWriter"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.lc.survey.model.SurveyWriter"),
			true);
	public static long ISCOMPLETE_COLUMN_BITMASK = 1L;
	public static long ISPREVIEW_COLUMN_BITMASK = 2L;
	public static long SURVEYMAINID_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.lc.survey.model.SurveyWriter"));

	public SurveyWriterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _surveyWriterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSurveyWriterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _surveyWriterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SurveyWriter.class;
	}

	@Override
	public String getModelClassName() {
		return SurveyWriter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("surveyWriterId", getSurveyWriterId());
		attributes.put("surveyMainId", getSurveyMainId());
		attributes.put("isPreview", getIsPreview());
		attributes.put("isComplete", getIsComplete());
		attributes.put("completionTime", getCompletionTime());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long surveyWriterId = (Long)attributes.get("surveyWriterId");

		if (surveyWriterId != null) {
			setSurveyWriterId(surveyWriterId);
		}

		Long surveyMainId = (Long)attributes.get("surveyMainId");

		if (surveyMainId != null) {
			setSurveyMainId(surveyMainId);
		}

		Boolean isPreview = (Boolean)attributes.get("isPreview");

		if (isPreview != null) {
			setIsPreview(isPreview);
		}

		Boolean isComplete = (Boolean)attributes.get("isComplete");

		if (isComplete != null) {
			setIsComplete(isComplete);
		}

		Long completionTime = (Long)attributes.get("completionTime");

		if (completionTime != null) {
			setCompletionTime(completionTime);
		}

		Long creatorId = (Long)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Long createDate = (Long)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@Override
	public long getSurveyWriterId() {
		return _surveyWriterId;
	}

	@Override
	public void setSurveyWriterId(long surveyWriterId) {
		_surveyWriterId = surveyWriterId;
	}

	@Override
	public long getSurveyMainId() {
		return _surveyMainId;
	}

	@Override
	public void setSurveyMainId(long surveyMainId) {
		_columnBitmask |= SURVEYMAINID_COLUMN_BITMASK;

		if (!_setOriginalSurveyMainId) {
			_setOriginalSurveyMainId = true;

			_originalSurveyMainId = _surveyMainId;
		}

		_surveyMainId = surveyMainId;
	}

	public long getOriginalSurveyMainId() {
		return _originalSurveyMainId;
	}

	@Override
	public Boolean getIsPreview() {
		return _isPreview;
	}

	@Override
	public void setIsPreview(Boolean isPreview) {
		_columnBitmask |= ISPREVIEW_COLUMN_BITMASK;

		if (!_setOriginalIsPreview) {
			_setOriginalIsPreview = true;

			_originalIsPreview = _isPreview;
		}

		_isPreview = isPreview;
	}

	public Boolean getOriginalIsPreview() {
		return _originalIsPreview;
	}

	@Override
	public Boolean getIsComplete() {
		return _isComplete;
	}

	@Override
	public void setIsComplete(Boolean isComplete) {
		_columnBitmask |= ISCOMPLETE_COLUMN_BITMASK;

		if (!_setOriginalIsComplete) {
			_setOriginalIsComplete = true;

			_originalIsComplete = _isComplete;
		}

		_isComplete = isComplete;
	}

	public Boolean getOriginalIsComplete() {
		return _originalIsComplete;
	}

	@Override
	public long getCompletionTime() {
		return _completionTime;
	}

	@Override
	public void setCompletionTime(long completionTime) {
		_completionTime = completionTime;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public long getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(long createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SurveyWriter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SurveyWriter toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SurveyWriter)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SurveyWriterImpl surveyWriterImpl = new SurveyWriterImpl();

		surveyWriterImpl.setSurveyWriterId(getSurveyWriterId());
		surveyWriterImpl.setSurveyMainId(getSurveyMainId());
		surveyWriterImpl.setIsPreview(getIsPreview());
		surveyWriterImpl.setIsComplete(getIsComplete());
		surveyWriterImpl.setCompletionTime(getCompletionTime());
		surveyWriterImpl.setCreatorId(getCreatorId());
		surveyWriterImpl.setCreateDate(getCreateDate());

		surveyWriterImpl.resetOriginalValues();

		return surveyWriterImpl;
	}

	@Override
	public int compareTo(SurveyWriter surveyWriter) {
		int value = 0;

		if (getCreateDate() < surveyWriter.getCreateDate()) {
			value = -1;
		}
		else if (getCreateDate() > surveyWriter.getCreateDate()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SurveyWriter)) {
			return false;
		}

		SurveyWriter surveyWriter = (SurveyWriter)obj;

		long primaryKey = surveyWriter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SurveyWriterModelImpl surveyWriterModelImpl = this;

		surveyWriterModelImpl._originalSurveyMainId = surveyWriterModelImpl._surveyMainId;

		surveyWriterModelImpl._setOriginalSurveyMainId = false;

		surveyWriterModelImpl._originalIsPreview = surveyWriterModelImpl._isPreview;

		surveyWriterModelImpl._setOriginalIsPreview = false;

		surveyWriterModelImpl._originalIsComplete = surveyWriterModelImpl._isComplete;

		surveyWriterModelImpl._setOriginalIsComplete = false;

		surveyWriterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SurveyWriter> toCacheModel() {
		SurveyWriterCacheModel surveyWriterCacheModel = new SurveyWriterCacheModel();

		surveyWriterCacheModel.surveyWriterId = getSurveyWriterId();

		surveyWriterCacheModel.surveyMainId = getSurveyMainId();

		surveyWriterCacheModel.isPreview = getIsPreview();

		surveyWriterCacheModel.isComplete = getIsComplete();

		surveyWriterCacheModel.completionTime = getCompletionTime();

		surveyWriterCacheModel.creatorId = getCreatorId();

		surveyWriterCacheModel.createDate = getCreateDate();

		return surveyWriterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{surveyWriterId=");
		sb.append(getSurveyWriterId());
		sb.append(", surveyMainId=");
		sb.append(getSurveyMainId());
		sb.append(", isPreview=");
		sb.append(getIsPreview());
		sb.append(", isComplete=");
		sb.append(getIsComplete());
		sb.append(", completionTime=");
		sb.append(getCompletionTime());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.lc.survey.model.SurveyWriter");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surveyWriterId</column-name><column-value><![CDATA[");
		sb.append(getSurveyWriterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyMainId</column-name><column-value><![CDATA[");
		sb.append(getSurveyMainId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isPreview</column-name><column-value><![CDATA[");
		sb.append(getIsPreview());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isComplete</column-name><column-value><![CDATA[");
		sb.append(getIsComplete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>completionTime</column-name><column-value><![CDATA[");
		sb.append(getCompletionTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SurveyWriter.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SurveyWriter.class
		};
	private long _surveyWriterId;
	private long _surveyMainId;
	private long _originalSurveyMainId;
	private boolean _setOriginalSurveyMainId;
	private Boolean _isPreview;
	private Boolean _originalIsPreview;
	private boolean _setOriginalIsPreview;
	private Boolean _isComplete;
	private Boolean _originalIsComplete;
	private boolean _setOriginalIsComplete;
	private long _completionTime;
	private long _creatorId;
	private long _createDate;
	private long _columnBitmask;
	private SurveyWriter _escapedModel;
}