/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lc.survey.model.impl;

import com.lc.survey.model.SurveyFile;
import com.lc.survey.model.SurveyFileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SurveyFile service. Represents a row in the &quot;lc_SurveyFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.lc.survey.model.SurveyFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveyFileImpl}.
 * </p>
 *
 * @author kevin
 * @see SurveyFileImpl
 * @see com.lc.survey.model.SurveyFile
 * @see com.lc.survey.model.SurveyFileModel
 * @generated
 */
public class SurveyFileModelImpl extends BaseModelImpl<SurveyFile>
	implements SurveyFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a survey file model instance should use the {@link com.lc.survey.model.SurveyFile} interface instead.
	 */
	public static final String TABLE_NAME = "lc_SurveyFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surveyFileId", Types.BIGINT },
			{ "surveyMainId", Types.BIGINT },
			{ "fileName", Types.VARCHAR },
			{ "creatorId", Types.BIGINT },
			{ "createDate", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table lc_SurveyFile (surveyFileId LONG not null primary key,surveyMainId LONG,fileName VARCHAR(150) null,creatorId LONG,createDate LONG)";
	public static final String TABLE_SQL_DROP = "drop table lc_SurveyFile";
	public static final String ORDER_BY_JPQL = " ORDER BY surveyFile.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY lc_SurveyFile.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.lc.survey.model.SurveyFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.lc.survey.model.SurveyFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.lc.survey.model.SurveyFile"),
			true);
	public static long SURVEYMAINID_COLUMN_BITMASK = 1L;
	public static long CREATEDATE_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.lc.survey.model.SurveyFile"));

	public SurveyFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _surveyFileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSurveyFileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _surveyFileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SurveyFile.class;
	}

	@Override
	public String getModelClassName() {
		return SurveyFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("surveyFileId", getSurveyFileId());
		attributes.put("surveyMainId", getSurveyMainId());
		attributes.put("fileName", getFileName());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long surveyFileId = (Long)attributes.get("surveyFileId");

		if (surveyFileId != null) {
			setSurveyFileId(surveyFileId);
		}

		Long surveyMainId = (Long)attributes.get("surveyMainId");

		if (surveyMainId != null) {
			setSurveyMainId(surveyMainId);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		Long creatorId = (Long)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Long createDate = (Long)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@Override
	public long getSurveyFileId() {
		return _surveyFileId;
	}

	@Override
	public void setSurveyFileId(long surveyFileId) {
		_surveyFileId = surveyFileId;
	}

	@Override
	public long getSurveyMainId() {
		return _surveyMainId;
	}

	@Override
	public void setSurveyMainId(long surveyMainId) {
		_columnBitmask |= SURVEYMAINID_COLUMN_BITMASK;

		if (!_setOriginalSurveyMainId) {
			_setOriginalSurveyMainId = true;

			_originalSurveyMainId = _surveyMainId;
		}

		_surveyMainId = surveyMainId;
	}

	public long getOriginalSurveyMainId() {
		return _originalSurveyMainId;
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public long getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(long createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SurveyFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SurveyFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SurveyFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SurveyFileImpl surveyFileImpl = new SurveyFileImpl();

		surveyFileImpl.setSurveyFileId(getSurveyFileId());
		surveyFileImpl.setSurveyMainId(getSurveyMainId());
		surveyFileImpl.setFileName(getFileName());
		surveyFileImpl.setCreatorId(getCreatorId());
		surveyFileImpl.setCreateDate(getCreateDate());

		surveyFileImpl.resetOriginalValues();

		return surveyFileImpl;
	}

	@Override
	public int compareTo(SurveyFile surveyFile) {
		int value = 0;

		if (getCreateDate() < surveyFile.getCreateDate()) {
			value = -1;
		}
		else if (getCreateDate() > surveyFile.getCreateDate()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SurveyFile)) {
			return false;
		}

		SurveyFile surveyFile = (SurveyFile)obj;

		long primaryKey = surveyFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SurveyFileModelImpl surveyFileModelImpl = this;

		surveyFileModelImpl._originalSurveyMainId = surveyFileModelImpl._surveyMainId;

		surveyFileModelImpl._setOriginalSurveyMainId = false;

		surveyFileModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SurveyFile> toCacheModel() {
		SurveyFileCacheModel surveyFileCacheModel = new SurveyFileCacheModel();

		surveyFileCacheModel.surveyFileId = getSurveyFileId();

		surveyFileCacheModel.surveyMainId = getSurveyMainId();

		surveyFileCacheModel.fileName = getFileName();

		String fileName = surveyFileCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			surveyFileCacheModel.fileName = null;
		}

		surveyFileCacheModel.creatorId = getCreatorId();

		surveyFileCacheModel.createDate = getCreateDate();

		return surveyFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{surveyFileId=");
		sb.append(getSurveyFileId());
		sb.append(", surveyMainId=");
		sb.append(getSurveyMainId());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.lc.survey.model.SurveyFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surveyFileId</column-name><column-value><![CDATA[");
		sb.append(getSurveyFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyMainId</column-name><column-value><![CDATA[");
		sb.append(getSurveyMainId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SurveyFile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SurveyFile.class
		};
	private long _surveyFileId;
	private long _surveyMainId;
	private long _originalSurveyMainId;
	private boolean _setOriginalSurveyMainId;
	private String _fileName;
	private long _creatorId;
	private long _createDate;
	private long _columnBitmask;
	private SurveyFile _escapedModel;
}